# Generated by Django 3.2.20 on 2024-06-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0021_auto_20221031_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.TextField()),
                ('paper_id', models.TextField()),
                ('hgvs_c', models.CharField(max_length=30)),
                ('hgvs_p', models.CharField(max_length=30)),
                ('paper_variant', models.TextField()),
                ('transcript', models.TextField()),
                ('gnomad_frequency', models.TextField()),
                ('individual_id', models.TextField()),
                ('phenotype', models.TextField()),
                ('zygosity', models.CharField(max_length=30)),
                ('variant_inheritance', models.CharField(max_length=60)),
                ('variant_type', models.CharField(max_length=30)),
                ('study_type', models.CharField(max_length=30)),
                ('engineered_cells', models.BooleanField()),
                ('patient_cells_tissues', models.BooleanField()),
                ('animal_model', models.BooleanField()),
                ('citation', models.TextField()),
                ('link', models.TextField()),
                ('paper_title', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.geneinfo')),
            ],
        ),
    ]
