# Generated by Django 3.2.20 on 2023-12-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0021_auto_20221031_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.TextField()),
                ('hgvs_c', models.CharField(max_length=25)),
                ('hgvs_p', models.CharField(max_length=25)),
                ('phenotype', models.TextField()),
                ('zygosity', models.CharField(max_length=25)),
                ('variant_inheritance', models.CharField(max_length=25)),
                ('study_type', models.CharField(max_length=25)),
                ('functional_study', models.TextField()),
                ('variant_type', models.CharField(max_length=25)),
                ('paper_title', models.TextField()),
                ('link', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.geneinfo')),
            ],
        ),
    ]
