name: Build docker image (Azure)
on: workflow_dispatch

jobs:
  deploy_server:
    runs-on: ubuntu-latest

    env:
      AZURE_CR: msseqr01.azurecr.io

    steps:
    - name: "checkout seqr repo"
      uses: actions/checkout@v3

    - name: 'Set up image name variables'
      run: |
        # Set up container registry authentication for image push.
        echo "CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')" >> $GITHUB_ENV
        echo "CLIENT_PWD=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')" >> $GITHUB_ENV

        # Set up image name and tag.
        echo "SEQR_IMAGE=$AZURE_CR/seqr" >> $GITHUB_ENV
        echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

        echo "Build/push ${SEQR_IMAGE}:${IMAGE_TAG}"

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CR }}
        username: ${{ env.CLIENT_ID }}
        password: ${{ env.CLIENT_PWD }}
    - run: |
        docker build \
          --tag ${SEQR_IMAGE}:${IMAGE_TAG} \
          --tag ${SEQR_IMAGE}:latest \
          -f deploy/docker/seqr/Dockerfile .
        docker push ${SEQR_IMAGE}:${IMAGE_TAG}
        docker push ${SEQR_IMAGE}:latest
